### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by TB-DevAcc** [jo-jstrm/SmartHomeBuddy#83]
Various tasks related to the electron app and its GUI.

- [ ] improve Frame
- [ ] improve Home page
- [ ] improve Devices page 
- [ ] create Network Data page
- [ ] create Alert page
- [ ] create Counter measures page
- [ ] create Insights page 
- [ ] create Settings page
- [ ] improve logo and color scheme
